### ISSUE TITLE
Create unified file format

### ISSUE THREAD

**Issue by wutzi15** [NetzwerkTeilchenwelt/muonic4#6]
Use JSON as an unified file format for all output files written to disk.

**Comment by wutzi15** [comment]
Add Comments
Add Timestamps

**Comment by wutzi15** [comment]
Rename R0,1,2,3,4 to Rate_0, Rate_1...
Rename chan0,1,2,3 to Counts_0, Counts_1, ...

**Comment by CosmicLabDESY** [comment]
R-File
P-file (puls)
D-file (decay)
V-file (velocity)
RAW-file

**Comment by wutzi15** [comment]
R FIle:
[
{
    "date": "2021-01-06",
    "time": "15:20:28.690",
    "R0": 9.772782799902272,
    "Comment":  "Zentiwinkel 90",
    "temperature": 21.6,
    "pressure": 1024,
},
....
{
    "date": "2021-01-06",
    "time": "15:20:28.690",
    "R0": 10.42891346412913,
    "temperature": 21.6,
    "pressure": 1024,
    "Comment_cleared": true,
},
]

P File:
[
{
    "date": "2021-01-06",
    "time": "15:20:28.690",
    "temperature": 21.6,
    "pressure": 1024,
    "channel_0": [
        {
            "rising_edge": 16.25,
            "falling_edge":9960.0  
        },
         {
            "rising_edge": 16.25,
            "falling_edge":9960.0  
        }
    ],
    "channel_1": [
    ]...
    "Comment": "Hier ist ein Kommentar"
}
]

V File:
[
{
    "date": "2021-01-06",
    "time": "15:20:28.690",
    "temperature": 21.6,
    "pressure": 1024,
    "delta_t": 124.12,
    "Comment": "Ch0 is upper, ch1 is lower, distance: 0.9m"
},
...
]

D File: 
[
{
    "date": "2021-01-06",
    "time": "15:20:28.690",
    "temperature": 21.6,
    "pressure": 1024,
    "delta_t": 12.154,
    "Comment": "Double pulse in Channel 1"
}
]

**Comment by CosmicLabDESY** [comment]
update: the pressure and temperature infos do not need to be saved in the P-, D- und V-file

**Comment by CosmicLabDESY** [comment]
consider: if the things that are set on the DAQ card before a measurement (trigger condition, threshold voltage) should be added to the command line or if another line should be added (e.g. Settings)
